### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by dannymichel** [The-Tasty-Jaffa/Tasty-Jaffa-cogs#45]
I know v2 is no longer supported but i was wondering if anyone could help me anyway. I'm using `` tempvoice`` and it's been fine for a year, but today I'm getting 
```
Traceback (most recent call last):
  File "/home/bots/redbot/cogs/tempvoice.py", line 234, in voice
    channel = await self.bot.create_channel(ctx.message.server, name, perms, type=discord.ChannelType.voice)#creates a channel
  File "lib/discord/client.py", line 2162, in create_channel
    data = yield from self.http.create_channel(server.id, name, str(type), permission_overwrites=perms)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)
```
any help would be greatly appreciated.

**Comment by Dezyox** [comment]
Try again...

**Comment by The-Tasty-Jaffa** [comment]
Red V2 is EOL so I have no plans on updating the v2 cogs.
